-- ================================================================
-- Gestor de Materias — Supabase Schema
-- Paste this in: Supabase Dashboard → SQL Editor → Run
-- ================================================================

-- Each table stores one row per record:
--   id   → primary key (UUID string generated by the app)
--   data → full JSON blob (all model fields)

CREATE TABLE IF NOT EXISTS materias (
  id   TEXT PRIMARY KEY,
  data JSONB NOT NULL
);

CREATE TABLE IF NOT EXISTS tareas (
  id   TEXT PRIMARY KEY,
  data JSONB NOT NULL
);

CREATE TABLE IF NOT EXISTS notas (
  id   TEXT PRIMARY KEY,
  data JSONB NOT NULL
);

CREATE TABLE IF NOT EXISTS calificaciones (
  id   TEXT PRIMARY KEY,
  data JSONB NOT NULL
);

CREATE TABLE IF NOT EXISTS grupos (
  id   TEXT PRIMARY KEY,
  data JSONB NOT NULL
);

CREATE TABLE IF NOT EXISTS anuncios (
  id   TEXT PRIMARY KEY,
  data JSONB NOT NULL
);

-- PDFs metadata (file is stored in Supabase Storage bucket "pdfs")
CREATE TABLE IF NOT EXISTS pdfs (
  id   TEXT PRIMARY KEY,
  data JSONB NOT NULL
);

-- ── Optional: indexes for common JSONB queries ────────────────
-- Speeds up filtering tareas by materiaId or grupoId
CREATE INDEX IF NOT EXISTS idx_tareas_materia ON tareas ((data->>'materiaId'));
CREATE INDEX IF NOT EXISTS idx_tareas_grupo   ON tareas ((data->>'grupoId'));
CREATE INDEX IF NOT EXISTS idx_notas_materia  ON notas  ((data->>'materiaId'));
CREATE INDEX IF NOT EXISTS idx_cals_materia   ON calificaciones ((data->>'materiaId'));

-- ── Row Level Security (RLS) ──────────────────────────────────
-- If you want per-user data isolation, enable RLS on each table
-- and add policies tied to auth.uid(). For now, disable RLS so
-- the anon key has full read/write access (suitable for dev).
ALTER TABLE materias      DISABLE ROW LEVEL SECURITY;
ALTER TABLE tareas        DISABLE ROW LEVEL SECURITY;
ALTER TABLE notas         DISABLE ROW LEVEL SECURITY;
ALTER TABLE calificaciones DISABLE ROW LEVEL SECURITY;
ALTER TABLE grupos        DISABLE ROW LEVEL SECURITY;
ALTER TABLE anuncios      DISABLE ROW LEVEL SECURITY;
ALTER TABLE pdfs          DISABLE ROW LEVEL SECURITY;
